# Generated by Django 3.0.5 on 2020-04-07 18:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200407_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='city',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
