# Generated by Django 2.0 on 2020-04-08 17:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_trial_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='profile_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
